FROM ubuntu

RUN apt-get -y update
RUN apt-get -y install build-essential
RUN apt-get -y install libreadline-gplv2-dev libncursesw5-dev libssl-dev libsqlite3-dev tk-dev libgdbm-dev libc6-dev libbz2-dev

WORKDIR /opt
RUN apt-get -y install wget && wget http://python.org/ftp/python/2.7.5/Python-2.7.5.tgz && tar -xvf Python-2.7.5.tgz && cd Python-2.7.5 && ./configure && make && make install
RUN apt-get -y install wget && wget https://bootstrap.pypa.io/get-pip.py && python /opt/get-pip.py && pip install robotframework && pip install robotframework-selenium2library 

RUN wget https://github.com/pshorally/D4DAutomationScript/archive/master.zip && apt-get -y install unzip && unzip master.zip
RUN apt-get -y install xvfb firefox
ENV DISPLAY :99
ENV PYTHONPATH /opt/D4DAutomationScript-master/project_rl_catalyst/Common_Resources
CMD /usr/bin/Xvfb :99 &,/bin/bash